In [93]:
%pip install pandas matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (3.0.2)
Requirement already satisfied: matplotlib in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\annik\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\annik\appdata\roaming\python\python311\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\annik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\annik\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [94]:
import pandas as pd

In [95]:
matches = pd.read_csv("../datasets/matches.csv", index_col=0)

In [96]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [97]:
matches.shape

(1389, 27)

# 2 seasons * 20 squads * 38 matches

In [98]:
2*20*38

1520

# missing Liverpool 2021-2022

In [99]:
matches["team"].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Manchester City             71
Arsenal                     71
Tottenham Hotspur           71
Wolverhampton Wanderers     71
Crystal Palace              71
Leeds United                71
Burnley                     71
Chelsea                     70
Leicester City              70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [100]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,Leeds United,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,Chelsea,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,Arsenal,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,Aston Villa,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,Everton,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,West Ham,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,Leicester City,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,Brighton,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,Wolves,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,Fulham,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,Tottenham,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,Crystal Palace,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,West Brom,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,Newcastle Utd,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,Southampton,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,Manchester Utd,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,Burnley,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,Tottenham,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,West Ham,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,Brighton,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,Manchester City,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,Leicester City,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,Everton,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,Chelsea,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,Fulham,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,Wolves,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,Arsenal,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,Leeds United,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,Newcastle Utd,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,Southampton,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,Manchester Utd,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,West Brom,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [101]:
matches["round"].value_counts()

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 23    39
Matchweek 24    39
Matchweek 25    39
Matchweek 26    39
Matchweek 28    39
Matchweek 29    39
Matchweek 31    39
Matchweek 32    39
Matchweek 34    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [102]:
matches.dtypes

date                str
time                str
comp                str
round               str
day                 str
venue               str
result              str
gf              float64
ga              float64
opponent            str
xg              float64
xga             float64
poss            float64
attendance      float64
captain             str
formation           str
referee             str
match report        str
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team                str
dtype: object

In [103]:
del matches["comp"]

In [104]:
del matches["notes"]

In [105]:
matches["date"] = pd.to_datetime(matches["date"])

In [106]:
matches["target"] = (matches["result"] == "W").astype(int)

In [107]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
1,2021-08-15,16:30,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,1.9,...,Match Report,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0
2,2021-08-21,15:00,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,2.7,...,Match Report,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1
3,2021-08-28,12:30,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,3.8,...,Match Report,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1
4,2021-09-11,15:00,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,2.9,...,Match Report,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,1
6,2021-09-18,15:00,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,1.1,...,Match Report,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,0.5,...,Match Report,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United,0
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,0.7,...,Match Report,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United,0
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,1.6,...,Match Report,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,0.8,...,Match Report,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United,0
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,0.6,...,Match Report,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1

In [108]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [109]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [110]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype(int)

In [111]:
matches["day_code"] = matches["date"].dt.dayofweek

In [112]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,1.9,...,1.0,0.0,0.0,2022,Manchester City,0,0,18,16,6
2,2021-08-21,15:00,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,2.7,...,1.0,0.0,0.0,2022,Manchester City,1,1,15,15,5
3,2021-08-28,12:30,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,3.8,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,2.9,...,0.0,0.0,0.0,2022,Manchester City,1,0,10,15,5
6,2021-09-18,15:00,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,1.1,...,1.0,0.0,0.0,2022,Manchester City,0,1,17,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,0.5,...,0.0,0.0,0.0,2021,Sheffield United,0,0,18,19,6
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,0.7,...,1.0,0.0,0.0,2021,Sheffield United,0,1,6,15,5
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,1.6,...,0.0,0.0,0.0,2021,Sheffield United,1,0,7,19,6
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,0.8,...,1.0,0.0,0.0,2021,Sheffield United,0,0,14,18,2
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,0.6,...,0.0,0.0,0.0,2021,Sheffield United,1,1,4,16,6

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [114]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10,random_state=1)

In [115]:
train = matches[matches["date"] < '2022-01-01']

In [116]:
test = matches[matches["date"] > '2022-01-01']

In [125]:
test

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
31,2022-01-15,12:30,Matchweek 22,Sat,Home,W,1.0,0.0,Chelsea,0.7,...,1.0,0.0,0.0,2022,Manchester City,1,1,5,12,5
32,2022-01-22,17:30,Matchweek 23,Sat,Away,D,1.0,1.0,Southampton,1.6,...,0.0,0.0,0.0,2022,Manchester City,0,0,17,17,5
34,2022-02-09,19:45,Matchweek 24,Wed,Home,W,2.0,0.0,Brentford,2.0,...,0.0,1.0,1.0,2022,Manchester City,1,1,2,19,2
35,2022-02-12,17:30,Matchweek 25,Sat,Away,W,4.0,0.0,Norwich City,4.6,...,0.0,0.0,1.0,2022,Manchester City,1,0,15,17,5
37,2022-02-19,17:30,Matchweek 26,Sat,Home,L,2.0,3.0,Tottenham,2.1,...,0.0,1.0,1.0,2022,Manchester City,0,1,18,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,2022-03-13,14:00,Matchweek 29,Sun,Away,L,1.0,2.0,Leeds United,1.2,...,1.0,0.0,0.0,2022,Norwich City,0,0,9,14,6
34,2022-04-02,15:00,Matchweek 31,Sat,Away,D,0.0,0.0,Brighton,0.3,...,0.0,0.0,0.0,2022,Norwich City,0,0,3,15,5
35,2022-04-10,14:00,Matchweek 32,Sun,Home,W,2.0,0.0,Burnley,1.5,...,0.0,0.0,0.0,2022,Norwich City,1,1,4,14,6
36,2022-04-16,15:00,Matchweek 33,Sat,Away,L,2.0,3.0,Manchester Utd,1.9,...,1.0,0.0,0.0,2022,Norwich City,0,0,13,15,5
37,2022-04-23,15:00,Matchweek 34,Sat,Home,L,0.0,3.0,Newcastle Utd,0.7,...,1.0,0.0,0.0,2022,Norwich City,0,1,14,15,5

In [117]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [118]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [119]:
preds = rf.predict(test[predictors])

In [120]:
from sklearn.metrics import accuracy_score

In [121]:
error = accuracy_score(test["target"], preds)

In [122]:
error

0.6123188405797102

In [123]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)

In [124]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

ValueError: cannot reindex on an axis with duplicate labels

In [ ]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.4745762711864407

In [ ]:
grouped_matches = matches.groupby("team")

In [ ]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [ ]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed="left").mean()
    group[new_cols] = rolling_stats 
    group = group.dropna(subset=new_cols)
    return group

In [ ]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk","pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,1.5,...,17,5,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,1.1,...,12,5,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,1.5,...,12,5,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,1.6,...,16,6,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,1.3,...,17,5,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2022-03-14,20:00,Matchweek 29,Mon,Away,D,0.0,0.0,Crystal Palace,2.3,...,20,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
44,2022-04-02,15:00,Matchweek 31,Sat,Away,W,2.0,0.0,Burnley,1.8,...,15,5,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
46,2022-04-10,16:30,Matchweek 32,Sun,Home,D,2.0,2.0,Liverpool,2.0,...,16,6,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
49,2022-04-20,20:00,Matchweek 30,Wed,Home,W,3.0,0.0,Brighton,1.2,...,20,2,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
50,2022-04-23,15:00,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,3.0,...,15,5,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [ ]:
matches_rolling = matches.groupby("team").apply(lambda x:rolling_averages(x, cols, new_cols))

In [ ]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 6  2020-10-04  14:00   Matchweek 4  Sun  Home      W
                        7  2020-10-17  17:30   Matchweek 5  Sat  Away      L
                        9  2020-10-25  19:15   Matchweek 6  Sun  Home      L
                        11 2020-11-01  16:30   Matchweek 7  Sun  Away      W
                        13 2020-11-08  19:15   Matchweek 8  Sun  Home      L
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 32 2022-03-13  14:00  Matchweek 29  Sun  Away      W
                        33 2022-03-18  20:00  Matchweek 30  Fri  Home      L
                        34 2022-04-02  15:00  Matchweek 31  Sat  Home      W
                        35 2022-04-08  20:00  Matchweek 32  Fri  Away      L
                        36 2022-04-24  14:00  Matchweek 34  Sun  Away      L

                             gf   ga         opponent   xg  ...  hour  \
team                                                        ...
Arsenal                 6   2.0  1.0    Sheffield Utd  0.4  ...    14
                        7   0.0  1.0  Manchester City  0.9  ...    17
                        9   0.0  1.0   Leicester City  0.9  ...    19
                        11  1.0  0.0   Manchester Utd  1.1  ...    16
                        13  0.0  3.0      Aston Villa  1.5  ...    19
...                         ...  ...              ...  ...  ...   ...
Wolverhampton Wanderers 32  1.0  0.0          Everton  0.8  ...    14
                        33  2.0  3.0     Leeds United  0.8  ...    20
                        34  2.0  1.0      Aston Villa  1.2  ...    15
                        35  0.0  1.0    Newcastle Utd  0.3  ...    20
                        36  0.0  1.0          Burnley  0.7  ...    14

                            day_code  gf_rolling ga_rolling sh_rolling  \
team
Arsenal                 6          6    2.000000   1.333333   7.666667
                        7          5    1.666667   1.666667   5.333333
                        9          6    1.000000   1.666667   7.000000
                        11         6    0.666667   1.000000   9.666667
                        13         6    0.333333   0.666667   9.666667
...                              ...         ...        ...        ...
Wolverhampton Wanderers 32         6    1.333333   1.000000  12.333333
                        33         4    1.666667   0.666667  12.333333
                        34         5    2.333333   1.000000  13.000000
                        35         4    1.666667   1.333333  13.000000
                        36         6    1.333333   1.666667  10.000000

                           sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Arsenal                 6     3.666667    14.733333    0.666667    0.000000
                        7     3.666667    15.766667    0.000000    0.000000
                        9     3.666667    16.733333    0.666667    0.000000
                        11    4.000000    16.033333    1.000000    0.000000
                        13    2.666667    18.033333    1.000000    0.333333
...                                ...          ...         ...         ...
Wolverhampton Wanderers 32    3.666667    19.300000    0.000000    0.000000
                        33    4.333333    19.600000    0.000000    0.000000
                        34    5.333333    19.833333    0.000000    0.000000
                        35    5.000000    18.533333    0.000000    0.000000
                        36    4.666667    17.633333    0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 6        0.000000
                        7        0.000000
                        9        0.000000
                        11       0.000000
                        13       0.333333
...                                   ...
Wolverhampton Wanderers 32       0.000000
                        33       0.000000
                        34       0.000000
                        35       0.000000
                        36       0.000000

[1317 rows x 37 columns]

In [ ]:
matches_rolling = matches_rolling.droplevel('team')

In [ ]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,0.4,...,14,6,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,0.9,...,17,5,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,0.9,...,19,6,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,1.1,...,16,6,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,1.5,...,19,6,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,2022-03-13,14:00,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,0.8,...,14,6,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
33,2022-03-18,20:00,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,0.8,...,20,4,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
34,2022-04-02,15:00,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,1.2,...,15,5,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
35,2022-04-08,20:00,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,0.3,...,20,4,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
36,2022-04-24,14:00,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,0.7,...,14,6,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [ ]:
matches_rolling.index = range(matches_rolling.shape[0])

In [ ]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [ ]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [ ]:
error

0.625

In [ ]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

KeyError: "['team'] not in index"

In [ ]:
combined.head(10)

    actual  predicted
31       1          0
32       0          0
34       1          0
35       1          1
37       0          1
38       1          1
40       1          0
42       0          0
44       1          0
46       0          0

In [ ]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolerhampton Wanderers": "Wolves"}
mapping = MissingDict(**map_values)

In [ ]:
combined["new_team"] = combined["team"].map(mapping)

KeyError: 'team'

In [ ]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [ ]:
merged

In [ ]:
merged[(merged["predicted_x" == 1]) & (merged["predicted_y" == 0])]["actual_x"].value_counts()